# Generated by Django 5.2.4 on 2026-07-14 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('loan_type', models.CharField(choices=[('HOME', 'Home Loan'), ('PERSONAL', 'Personal Loan'), ('AUTO', 'Auto Loan'), ('LAP', 'Loan Against Property')], db_index=True, max_length=20)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tenure_months', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='branches.branch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
