# Generated by Django 5.2.4 on 2026-07-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('variables', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='variables', to='documents.document'),
        ),
    ]
