# Generated by Django 5.2.4 on 2026-07-14 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_account_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('disbursed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_principal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('emi_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('disbursed_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULTED', 'Defaulted')], db_index=True, default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan_account', to='applications.loanapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
