# Generated by Django 5.2.4 on 2026-07-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
