# Generated by Django 5.2.4 on 2026-07-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='content_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
