# Generated by Django 5.2.4 on 2026-07-15 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_template_content_json'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when template was approved', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved the template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='template',
            name='effective_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date when template becomes active', null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='lifecycle_status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='INACTIVE', help_text='Automatically derived from effective date', max_length=20),
        ),
        migrations.AddField(
            model_name='template',
            name='review_comments',
            field=models.TextField(blank=True, help_text='Comments from reviewer during approval'),
        ),
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='templatecomponent',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='templatestyle',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='templateversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
