# Generated by Django 5.2.4 on 2026-07-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_template_approved_at_template_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='templatecomponent',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='templatestyle',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='templateversion',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
    ]
