# Generated by Django 5.2.4 on 2026-07-16 06:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_alter_template_status_alter_templatecomponent_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='templateversion',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when version was approved', null=True),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='base_version',
            field=models.ForeignKey(blank=True, help_text='The approved version this draft is based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='templates.templateversion'),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='diff_data',
            field=models.JSONField(blank=True, default=dict, help_text='Stores the diff between this version and base_version'),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='version_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', help_text='Status of this version (DRAFT or APPROVED)', max_length=20),
        ),
        migrations.CreateModel(
            name='TemplateElementChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('element_id', models.CharField(db_index=True, help_text='Unique identifier of the element (from template JSON)', max_length=255)),
                ('change_type', models.CharField(choices=[('ADDED', 'Added'), ('MODIFIED', 'Modified'), ('DELETED', 'Deleted')], db_index=True, help_text='Type of change: ADDED, MODIFIED, or DELETED', max_length=20)),
                ('old_value', models.JSONField(blank=True, help_text='Original element data (null for ADDED)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New element data (null for DELETED)', null=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVERTED', 'Reverted')], db_index=True, default='PENDING', help_text='Approval status of this specific change', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when change was reviewed', null=True)),
                ('review_comment', models.TextField(blank=True, help_text='Comment from reviewer about this change')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='User who reviewed this change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_changes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(help_text='The draft version containing this change', on_delete=django.db.models.deletion.CASCADE, related_name='element_changes', to='templates.templateversion')),
            ],
            options={
                'verbose_name': 'Template Element Change',
                'verbose_name_plural': 'Template Element Changes',
                'indexes': [models.Index(fields=['version', 'element_id'], name='templates_t_version_38c37e_idx'), models.Index(fields=['version', 'approval_status'], name='templates_t_version_1776ec_idx')],
            },
        ),
    ]
