# Generated by Django 5.2.4 on 2026-07-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_templateversion_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='page_orientation',
            field=models.CharField(default='PORTRAIT', help_text='Page orientation (PORTRAIT or LANDSCAPE)', max_length=10),
        ),
        migrations.AddField(
            model_name='template',
            name='page_size',
            field=models.CharField(default='A4', help_text='Page size for rendering (A4, A3, LETTER, etc.)', max_length=10),
        ),
        migrations.AddField(
            model_name='template',
            name='prosemirror_json',
            field=models.JSONField(blank=True, default=dict, help_text='ProseMirror document (single source of truth)'),
        ),
        migrations.AlterField(
            model_name='template',
            name='content_json',
            field=models.TextField(blank=True, help_text='DEPRECATED: Composite format. Use prosemirror_json instead.', null=True),
        ),
        migrations.AlterField(
            model_name='templateversion',
            name='version_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FOR_REVIEW', 'For Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', help_text='Status of this version (DRAFT or APPROVED)', max_length=20),
        ),
    ]
