# Generated by Django 5.2.4 on 2026-07-13 06:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('connector_type', models.CharField(choices=[('DATABASE', 'Database'), ('API', 'API'), ('FILE', 'File'), ('QUEUE', 'Queue'), ('WEBHOOK', 'Webhook')], db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('host', models.CharField(blank=True, db_index=True, max_length=255)),
                ('port', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('database_name', models.CharField(blank=True, db_index=True, max_length=150)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('api_base_url', models.URLField(blank=True, max_length=500)),
                ('timeout', models.PositiveIntegerField(default=30)),
                ('retry_count', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connector',
                'verbose_name_plural': 'Connectors',
            },
        ),
        migrations.CreateModel(
            name='ConnectorConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('configuration_json', models.JSONField(blank=True, default=dict)),
                ('headers_json', models.JSONField(blank=True, default=dict)),
                ('authentication_type', models.CharField(choices=[('NONE', 'None'), ('BASIC', 'Basic'), ('API_KEY', 'API Key'), ('BEARER_TOKEN', 'Bearer Token'), ('OAUTH2', 'OAuth2')], db_index=True, max_length=50)),
                ('authentication_json', models.JSONField(blank=True, default=dict)),
                ('connector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='connectors.connector')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connector Configuration',
                'verbose_name_plural': 'Connector Configurations',
            },
        ),
    ]
